config/routes.rb
Article3D::Application.routes.draw do
  get '/' => redirect("browse")
  post 'users' => 'users#create'
  get 'browse' => 'articles#index', :as => :articles
  post 'browse' => 'articles#create'
  get 'articles/create' => 'articles#new', :as => :new_article
  get 'sign_up' => 'users#new', :as => :new_user
  delete 'sign_out' => 'auths#destroy', :as => :auths
  get 'sign_in' => 'auths#new', :as => :new_auth
  get 'categories' => 'categories#index', :as => :categories
  resources :auths, only:[:create]

end

app/models/article.rb
require 'paperclip'
class Article
  include Mongoid::Document
  include Mongoid::Paperclip
  field :title, type: String
  # field :audio_file, type: String
  field :image_files, type: Array
  field :printing_file, type: String
  field :video_file, type: String
  field :hypothesis, type: String
  field :description, type: String

  belongs_to :user
  belongs_to :category

  embeds_many :pictures, :cascade_callbacks => true, :validate => false
  accepts_nested_attributes_for :pictures
  # attr_accessible :pictures_attributes
  
  has_mongoid_attached_file :audio_file,
    :path => ':attachment/:id/:style.:extension',
    :storage => :s3,
    :bucket => "articlethreedee"
  do_not_validate_attachment_file_type :audio_file

end

app/models/category.rb
class Category
  include Mongoid::Document
  field :link, type: String
  field :launch_image, type: String
  has_many :articles
end

app/models/picture.rb
class Picture
  include Mongoid::Document
  include Mongoid::Paperclip

  embedded_in :article, :inverse_of => :pictures
  # attr_accessible :attachment

  has_mongoid_attached_file :attachment,
    :path           => ':attachment/:id/:style.:extension',
    :storage        => :s3,
    :bucket => "articlethreedee",
    :styles => {
      :original => ['1920x1680>', :jpg],
      :small    => ['100x100#',   :jpg],
      :medium   => ['250x250',    :jpg],
      :large    => ['500x500>',   :jpg]
    },
    :convert_options => { :all => '-background white -flatten +matte' }
    do_not_validate_attachment_file_type :attachment
end

app/models/user.rb
require 'bcrypt'
class User
  include Mongoid::Document
  attr_accessor :password, :password_confirmation
  field :username, type: String
  field :hashed_password, type: String
  field :salt, type: String
  field :email_address, type: String
  field :first_name, type: String
  field :last_name, type: String
  field :avatar_path, type: String
  before_save :hash_the_password
  has_many :articles
  
  validates_uniqueness_of :username

  def passes_authentication?(password_to_check)
    BCrypt::Password.new(self.hashed_password).is_password?(password_to_check)
  end

  private
    def hash_the_password
        unless self.hashed_password
          self.hashed_password = BCrypt::Password.create(self.password)
          self.password = self.password_confirmation = nil
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper_method :current_user
  protect_from_forgery with: :exception

  def current_user
    
    if session[:user_id]
      User.find_by(id: session[:user_id])
    end
  end
end

app/controllers/articles_controller.rb
require 'aws'
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only:[:edit, :new, :create, :update, :destroy, :show]
  def index
    @articles = Article.all
  end

  def show
    
  end

  def edit
    
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      
      redirect_to articles_path
    else
      redirect_to new_article_path
    end

  end

  def update
    if @article.update(article_params)
      #redirect_to SOMETHING!!!
    end
  end

  def destroy
    if current_user
      @article.destroy
      #redirect_to SOMETHING!!!
    end
  end
  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title,:audio_file,:printing_file,:video_file,:hypothesis,:description, pictures_attributes: [:attachment])
    end

    def require_login
      unless current_user
        redirect_to new_auth_path
      end
    end
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  def new
    if current_user
      redirect_to users_path
    else
      @user = User.new
    end
  end
  
  def create
    user = User.where(username: params[:user][:username])
    if user.count > 0
      @user = user[0]
      if @user.passes_authentication?(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to articles_path
        # if @user.is_verified?
        #   session[:user_id] = @user.id
        #   redirect_to users_path
        # else
        #   redirect_to new_auth_path
        #   flash[:error] = "Please check your e-mail and verify your identity." 
        # end
      else
        redirect_to new_auth_path
        flash[:error] = 'Invalid username and/or password.  Please try again.'
      end
    else
      redirect_to new_auth_path
      flash[:error] = 'Invalid username and/or password.  Please try again.'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to new_auth_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    unless current_user
        @user = User.new
    else redirect_to articles_path
    end
  end

  def create
    creation = params.require(:user).permit(:username, :email_address,:password, :password_confirmation)
    @user = User.new(creation)
    if creation[:password] == creation[:password_confirmation] && @user.save
      

      redirect_to new_auth_path
      flash[:notice] = "A confirmation e-mail has been sent to your account."
    else
      redirect_to new_user_path
      flash[:error] = @user.save ? "Please confirm your password properly." : "Username already exists."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<h2>Create New Article</h2>
<div class = "container">
  <%= form_for(@article) do |a| %>
  <div>
    <%= a.label :post, "Title of experiment" %>
    <%= a.text_field :title %>
  </div>
  <div class="picture-upload">
    <%= a.label :post, "Picture File" %>
    <%= a.file_field "article_pictures_attributes_attachment", multiple: true, name:'article[pictures_attributes[][attachment]' %>
  </div>
  <div class="audio-upload">
    <%= a.label :post, "Audio File" %>
    <%= a.file_field :audio_file, class:"custom-file-input" %>
    <span class="fa fa-camera fa-2x"></span>
    <span class="fa fa-volumn fa-2x"></span>
    <span class="fa fa-gears fa-2x"></span>
  </div>
  <div>
    <%= a.label :post, "Hypothesis" %>
    <%= a.text_area :hypothesis %>
  </div>
  <div>
    <%= a.label :post, "Description" %>
    <%= a.text_area :description %>
  </div>
  <div class="submit">
    <%= a.submit %>
  </div>
<% end %>
</div>

app/views/articles/_friends.html.erb
koalasarethebest

app/views/articles/_popular.html.erb
fdfds

app/views/articles/_recent.html.erb
heyo

app/views/articles/edit.html.erb
edit.html.erb

app/views/articles/index.html.erb
<div class="clearfix">
  <div class="column">

  <h3>Recent</h3>
  <div class="img-scroll">
    <%= render partial:"articles/recent.html.erb" %>
  </div>

</div>


<div class="column">

  <h3>Popular</h3>
  <div class="img-scroll">
    <%= render partial:"articles/popular.html.erb" %>
  </div>

</div>

<div class="column">

  <h3>Friends</h3>

  <div class="img-scroll">
    <%= render partial:"articles/friends.html.erb" %>
  </div>

</div>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
show.html.erb

app/views/auths/_form.html.erb
<%= form_for @user, {url:'/auths', method:'post'} do |u| %>
    <%= u.text_field :username, :id=> "sign-username", :class=> "userform",:placeholder => "Username" %>
    <%= u.password_field :password, :id=> "sign-password",:class=> "userform", :placeholder => "Password" %>
    <%= u.submit "Sign In", :class => "userform"%>
<% end %>

app/views/auths/new.html.erb
<fieldset class="sign-in">
  <legend> Sign In </legend>
<div>
  <%= render 'form' %>
</div>
</fieldset>
<%= link_to 'Sign Up', new_user_path %>

app/views/categories/index.html.erb
<header class = "nr" id = "category-header"></header>

<ul id = "categories">
  <% @categories.each do |category| %>
    <li class = "nr" id= "<%= category.launch_image %>"></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Article3D</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
 
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header id = "main-header">
    <% if current_user %>
      Logged in as <%= current_user.username %>.  
      <%= link_to 'Sign Out', auths_path, {method: :delete} %>
    <% else %>
      <%= link_to 'Sign In', new_auth_path %> or <%= link_to 'Sign Up', new_user_path %>
    <% end %>
  </header>
  <div id = "main">
    <%= yield %>
  </div>
  <aside>
    <ul class="browse-menu">
      <li class="menu-recent nr">
        <a href="/browse/recent/"></a>
      </li>
      <li class="menu-popular nr">
        <a href="/browse/popular/"></a>
      </li>
      <li class="menu-friends nr">
        <a href="/browse/friends/"></a>
      </li>
      <li class="menu-category nr">
        <a href="/categories"></a>
      </li>
    </ul>
  </aside>
  <footer class = "clearfix">
    <a class="browse nr" href="/browse/"></a>
    <a class="request nr" href="/request/"></a>
    <a class="create nr" href="/articles/create/"></a>
    <a class="account nr" href="/account/"></a>
  </footer>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |u| %>
    <%= u.text_field :username, :placeholder => "Username" %>
    <%= u.password_field :password, :placeholder => "Password" %>
    <%= u.password_field :password_confirmation, :placeholder => "Confirm Password" %>
    <%= u.submit "Sign Up" %>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>